### ISSUE TITLE
Puzzle image goes off screen

### ISSUE THREAD

**Issue by infinitless** [tvdhout/Lichess-discord-bot#47]
The puzzle image goes off screen. E.g. the h file is off the screen and only partly visible.

**Comment by tvdhout** [comment]
I can't reproduce this. Can you share a screenshot? On what discord client are you experiencing this? mobile? windows mac?

**Comment by infinitless** [comment]
Mobile. Samsung Android. 
![Screenshot_20220824-205649_Discord](https://user-images.githubusercontent.com/87955275/186511582-537a57f5-8c43-4553-ad52-c9e1fc9eac28.jpg)

**Comment by tvdhout** [comment]
Thanks for the update. It seems this is an issue with discord on Android and perfectly square images.

https://support.discord.com/hc/en-us/community/posts/360068139831-Cut-of-Pictures

What's weirder is that it's a post from two years ago... Someone says reinstalling discord helps, maybe you could try that?
